export const MESSAGE_MEDIA_BUCKET_NAME = 'messageMedia';
export const MAX_MESSAGE_IMAGE_BYTES = 10 * 1024 * 1024;
export const MAX_VOICE_MESSAGE_BYTES = 10 * 1024 * 1024;
export const MAX_VOICE_MESSAGE_DURATION_MS = 5 * 60 * 1000;
export const MAX_VIDEO_MESSAGE_BYTES = 25 * 1024 * 1024;
export const MAX_FILE_MESSAGE_BYTES = 25 * 1024 * 1024;
export const MAX_MESSAGE_MEDIA_BYTES = Math.max(
  MAX_MESSAGE_IMAGE_BYTES,
  MAX_VOICE_MESSAGE_BYTES,
  MAX_VIDEO_MESSAGE_BYTES,
  MAX_FILE_MESSAGE_BYTES,
);
